const data = [
  {
    id: 1,
    columnTitle: "Tasks Not Assigned",
    backgroundColor: "#dff7e4",
    borderTopColor: "#93cb9d",
    otherBorders: "#c7e8ce",
    status: "Tasks Not Assigned",
  },
  {
    id: 2,
    columnTitle: "Boosted CRM",
    backgroundColor: "#daecf7",
    borderTopColor: "#98bfd7",
    otherBorders: "#c9deec",
    status: "Boosted CRM",
  },
  {
    id: 3,
    columnTitle: "Emranul Hassan",
    backgroundColor: "#f7edda",
    borderTopColor: "#d2bc93",
    otherBorders: "#e9deca",
    status: "Emranul Hassan",
  },
  {
    id: 4,
    columnTitle: "Hoang Tran Pham",
    backgroundColor: "#f7daef",
    borderTopColor: "#d095c0",
    otherBorders: "#eccce3",
    status: "Hoang Tran Pham",
  },
  {
    id: 5,
    columnTitle: "Maddie Hassan",
    backgroundColor: "#daf5f7",
    borderTopColor: "#99d1d3",
    otherBorders: "#cfe9ea",
    status: "Maddie Hassan",
  },
  {
    id: 6,
    columnTitle: "Rahul Sikdar",
    backgroundColor: "#dae0f7",
    borderTopColor: "#9ba7d6",
    otherBorders: "#c5cce7",
    status: "Rahul Sikdar",
  },
  {
    id: 7,
    columnTitle: "Michael Yana",
    backgroundColor: "#f7e2da",
    borderTopColor: "#d6ad9e",
    otherBorders: "#edd5cc",
    status: "Michael Yana",
  },
  {
    id: 8,
    columnTitle: "Tim R",
    backgroundColor: "#f7dae4",
    borderTopColor: "#dca2b6",
    otherBorders: "#eecbd7",
    status: "Tim R.",
  },
  {
    id: 9,
    columnTitle: "Baz Destiny",
    backgroundColor: "#dae0f7",
    borderTopColor: "#9ba7d6",
    otherBorders: "#c5cce7",
    status: "Baz Destiny",
  },
  {
    id: 10,
    columnTitle: "Rowel Sabas",
    backgroundColor: "#e7daf7",
    borderTopColor: "#ad93cd",
    otherBorders: "#d8c9eb",
    status: "Rowel Sabas",
  },
  {
    id: 11,
    columnTitle: "Sai Subramaniam",
    backgroundColor: "#f7edda",
    borderTopColor: "#d2bc93",
    otherBorders: "#e9deca",
    status: "Sai Subramaniam",
  },
  {
    id: 12,
    columnTitle: "Abhishek Dudeja",
    backgroundColor: "#dae0f7",
    borderTopColor: "#9ba7d6",
    otherBorders: "#c5cce7",
    status: "Abhishek Dudeja",
  },
  {
    id: 13,
    columnTitle: "Ankush Gupta",
    backgroundColor: "#daf5f7",
    borderTopColor: "#99d1d3",
    otherBorders: "#cfe9ea",
    status: "Ankush Gupta",
  },
  {
    id: 14,
    columnTitle: "Goyal Piyush",
    backgroundColor: "#f7dae4",
    borderTopColor: "#dca2b6",
    otherBorders: "#eecbd7",
    status: "Goyal Piyush",
  },
];

export default data;
